### ISSUE TITLE
Tooltip Formatter Callback Context

### ISSUE THREAD

**Issue by matthiaskomarek** [gevgeny/angular2-highcharts#177]
Hi, i am trying to write a custom tooltip formatter. But when i use the `options.tooltip.formatter` callback. The `this` context inside the formatter callback gets bound to the tooltip and so i cant access my component data.

You can see this issue here:
http://plnkr.co/edit/0ZJ29O8YqxvNW5486CDI?p=preview

**Comment by lebnic** [comment]
Same here...

**Comment by matthiaskomarek** [comment]
#206 will fix this

**Comment by gevgeny** [comment]
This default Highcharts behavior so you can have access to tooltip dynamic props like 'points'. If you wan to safe context just use standard js technics like bind or arrow functions.

**Comment by matthiaskomarek** [comment]
Bind or Arrow Functions dont solve the problem, as you can see on my provided plunker: the actual value of the hovered datapoint is the `this` context inside the tooltip formatter function.
If i use bind or an arrow function, i will set the context to my component and i will lose the datapoint value.

**Comment by abelkbil** [comment]
@gevgeny @matthiaskomarek How did you solve this issue; I do have the same need. 
http://jsfiddle.net/abelutt16/r32orj85/11/

The printing content need to be  passed to an angular 2 component class function. Since this reference is not available; How can i expect to pass this data to another function. Kindly support. @matthiaskomarek  commit is not added to this lib too.

Fat arrow didn't work for me.

```
constructor(
  ) {
     this.chart_options = {
        title : false,
        chart: {
            zoomType: 'x'
        },
        tooltip: {
          shared: true,
          crosshairs: [true, false],
          formatter: function() {
            var scooterPoints=[];
            var string = this.x + '<br>';
            Highcharts.each(this.points, function(p) {
              var sooterPoint = {
                "name":p.series.name,
                "value":p.y
              }
              scooterPoints.push(sooterPoint);
              string += p.series.name + ': <strong>' + p.y + '</strong><br>'
            });
            console.log(scooterPoints);
            //this.valueArrayUpdate(scooterPoints);
            return string;
          }
          
        },
        yAxis: {
          plotLines: []
        },
        series: []
      };
  }
```

This is the constructor of my component.

**Comment by matthiaskomarek** [comment]
@abelkbil Unfortunately you cant solve this issue with the current version of this library, so i have forked the hole lib and implemented my solution there.
Here is a link to the doku which describes how you can solve this issue with my fork:
https://github.com/kiwigrid/angular2-highcharts#tooltip-formatter-for-chart-object

**Comment by Nelladel** [comment]
This has to do with lexical scopes. 
There is a way how you can solve the issue, and it involves including in the Highchart's closure a reference to the component's `this`. Anywhere you like (for instance in the `ngOninit` lifecycle hook -once the chart object has been initialised-) do something like this: 

```js
ngOnInit() {
    var comp = this;
    this.chart.options.tooltip.formatter = function() {
        console.log(this); // points to the Highchart's formatter scope
        console.log(comp); // points to the Component's scope    
    }
}
```

This way you can reference methods, properties, or injected dependencies in the component, as well as the series, point, and any other information from the formatter's scope.

**Comment by lebnic** [comment]
@Nelladel your workaround works, thanks !

However, it is not a "perfect" solution, and makes the code a bit "unclear". So if anybody has an even better fix (that allows for the use of "this" within the scope of the formatter), please share. Could there be a way to "re-assign" the "formatter's this" instead ?

**Comment by totszwai** [comment]
There is another way to get around this. Since `Highcharts` is passing its `chart.tooltip` to the callback as the `TooltipFormatterContextObject`, you could extend the object with your own custom function.

```
export interface IExtendedHighchartsObject {
  getHostComponent: () => IMyWrapperComponent | any;
  getOtherStuffYouWannaGet: () => IMyOtherStuff | any
}
```

You create your chart, in the callback, you do this:
```
chart(
  this.chartContainerRef.element.nativeElement,
  myOptions,
  (chartObject: Highcharts.Chart) => {
      this.extendHighchartsObjects(chartObject);
  });
```

You extend the tooltip object with your own implementation:
```
  private extendHighchartsObjects(chartObject: Highcharts.Chart) {
    // Extending Highcharts.Tooltip
    if (chartObject.tooltip) {
      const tt: IExtendedHighchartsObject = chartObject.tooltip as any;
      tt.getHostComponent = () => this;
      tt.getOtherStuffYouWannaGet = () => { return { hello: 'world' }; };
    }
  }
```

Then in your formatter, you can now do this:
```
tooltip: {
  formatter: function(tooltip) {
    const myStuff = (tooltip as IExtendedHighchartsObject).getOtherStuffYouWannaGet();
    console.log(myStuff.hello); // will print 'world'
  }
}
```

This is of course much more complicated, but I believe this solution is cleaner.

Update: I tested this mechanism on DataLabels' formatter too and it worked.
```
    const extendThat = (that) => {
      if (that) {
        const obj = that as IExtendedHighchartsObject;
        obj.getHostComponent = () => this;
        obj.getOtherStuffYouWannaGet = () => { return { hello: 'world' }; };
      }
    };

    // Extending Highcharts DataLabels
    const plotOptions = _.get(chartObject, 'userOptions.plotOptions');
    if (plotOptions) {
      _.keys(plotOptions).forEach((key) => {
        // there are formatters inside dataLabels, when the formatter is called
        // the DataLabels object is passed to the formatter
        extendThat(plotOptions[key].dataLabels);
      });
    }
```

PS: This mechanism should work on all formatters across Highcharts, in fact it should also work on other Highcharts' object as well, as long as you can find out which object blob Highcharts is passing you can basically extend it however you want. Is just JavaScript under the hood so, just `as any` and you can play with it any way you want. :)
