### ISSUE TITLE
updated npm package to solve the typings error

### ISSUE THREAD

**Issue by sisirap** [gevgeny/angular2-highcharts#2]
Hi i am using this latest version of this and i keep hitting the browser.d.ts typings error which looking at the commits seems to be fixed but the npm package isn't updated

**Comment by gevgeny** [comment]
Could you provide some more details about the error?

**Comment by sisirap** [comment]
the browser typing is being referenced to this path
/// <reference path="../node_modules/angular2/typings/browser.d.ts" />

instead of /// <reference path="../../../typings/browser.d.ts" />

and i also see errors about 'cannot find symbol EventEmitter' in ChartCompoent.d.ts

**Comment by ahmelsayed** [comment]
[this](https://github.com/gevgeny/angular2-highcharts/blob/1d29e016df50a540a5b0a0a65abf0db0940f1ed8/src/ChartComponent.ts#L2) Doesn't always work with npm 3 because npm 3 flattens the `node_modules` folder so you're not gurenteed to have `angular2` folder under your `node_modules` Looking at the repo, I'm pretty sure ecbc82f49af4ee3091379612fad3d6f5bb230f59 fixes it, but it's not in the npm package :)

**Comment by sisirap** [comment]
the current version for this project says 0.0.3 looking at the commits looks like this refers to this commit , https://github.com/gevgeny/angular2-highcharts/commit/1d29e016df50a540a5b0a0a65abf0db0940f1ed8
 the one that should fix this issue probably has not updated to the package?

**Comment by gevgeny** [comment]
@sisirap Going to update the package this weekend
