### ISSUE TITLE
How to redraw chart

### ISSUE THREAD

**Issue by rachelmad** [gevgeny/angular2-highcharts#25]
I currently have it such that the data displayed in my charts needs to change based on a button click. I may have to add or delete a series, change the date ranges displayed, or display new data altogether. 

I've found that by editing 
`this.options.series`
I can easily manipulate the data displayed.

However, since the chart isn't automatically redrawn on change, the changes to the series aren't reflected in the charts.

How do I redraw a chart using this library?

**Comment by rachelmad** [comment]
Update:

I was wrong. When I do
`this.options.series = Array<Series>
console.log(this.options.series)`
I see that my series data has been updated.

Then when I call
`this.chart.redraw`
and step through the code, I also see that the chart is redrawn.

However, while redrawing the chart, Highcharts isn't able to detect that there were changes to this.options.series. My theory is that I need to access the Highcharts Series object and use the setData() method. I don't know how to do this though. Any tips?

**Comment by gevgeny** [comment]
`angular-highcharts` is just a thin wrapper of the [Highcharts](http://www.highcharts.com/) library. I understand that you expect more angular-way behaviour like data binding with appropriate redrawing. But it is barely possible to implement it without redundant complications and performance decrease because almost all options can be dynamic. So my idea was to avoid any additional logic more than just a sugar (like events for series and options). In the other hand Highcharts has great [API](http://api.highcharts.com/highcharts#Chart) for dynamic manipulations with chart and `angular-highcharts` [provides you access](https://github.com/gevgeny/angular2-highcharts#dynamic-interaction-with-chart-object) to the original chart object.

**Comment by sairam0903** [comment]
I know it's late, but this could help some one.

In HTML:
`<chart [options]="options" (load)="saveInstance($event.context)"></chart>`

In component:
```
chart: Object;
saveInstance(chartInstance): void {
     this.chart = chartInstance;
}
```

and to update the chart with new data:
```
updateSeriesData(data: Array<any>): void {
   this.chart.series[0].setData(data);
}
```

This will redraw the chart. It worked in my case. If anyone has a better way plz correct me.

**Comment by Devmikola** [comment]
Thanks sairam0903.
Note that variable data will be changed inside function setData, so your external variable will be changed to. I faced with this because i did not wrap setting data by additional function.
