### ISSUE TITLE
How to destroy chart and build it again?

### ISSUE THREAD

**Issue by desano** [gevgeny/angular2-highcharts#46]
I want to destroy chart and build it again. In jQuery I can do it like here...

chart1.destroy();
chart1 = new Highcharts.Chart(optionsChart1,highlightSer);

Code from http://stackoverflow.com/questions/7880978/highcharts-jquery-destroy-and-rebuild-chart-with-original-options

...but how can I do this in Angular 2?

**Comment by gevgeny** [comment]
Need to take into consideration that in our case chart is a component which is integrated into DOM under `chart` tag. You cannot just imperatively do `chartComponent.destroy()`. I think it would make sense to handle `ngOnDestroy` event in order to do `ngOnDestroy` but it still does not solve you problem directly and you need decide how you are going to recreate your components.

**Comment by desano** [comment]
Can you give me some examples how can I recreate component? I don't know how can I do some operations on component which is integrated into DOM.

**Comment by gevgeny** [comment]
https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html

**Comment by gevgeny** [comment]
In other words if you really need to create new chart with new data and you decided that setting new data into the existing chart is not suitable for you so it would be correct to show new one and hide old one

``` html
<chart name="myNewChart" *ngIf="toggleChart"/>
<chart name="myOldChart" *ngIf="!toggleChart"/>
```

**Comment by desano** [comment]
Ok, thank you. I solved my problem with setting ngIf variable to false and later to true to rebuild the same chart with new data. NgIF is a solution for everything ;)

**Comment by gevgeny** [comment]
Should work despite it is little hacky ;)
