### ISSUE TITLE
Support for RC5?

### ISSUE THREAD

**Issue by sidewaiise** [gevgeny/angular2-highcharts#57]
Does this library support Angular 2 RC5?

**Comment by gevgeny** [comment]
No at the moment. But feel free to pull request

**Comment by gevgeny** [comment]
Elsewhere I am going to wait angular2 release because looks like angular2 devs don't want to freeze API changes even during RC.

**Comment by andvasp** [comment]
Hi @gevgeny.  It is not intended API changes in the RC6. So would be good to give support for RC6.

**Comment by singhjusraj** [comment]
There won't be any breaking changes in API from RC6 onward. Please update this library as many people are currently unable to generate production builds because this library is not up to date

EDIT : @gevgeny Angular's final version is live now. If you can update this library that will be great.

Thanks

**Comment by hoswey** [comment]
vote+1, I face the same issue

**Comment by electricessence** [comment]
Support RC6!? :/

**Comment by lilling** [comment]
+1

**Comment by lilling** [comment]
@gevgeny thank you for your awesome wrapper! it's been very helpful til rc.5 breaking changes.
so now angular 2 is finally here! can we expect an update here to?

**Comment by ravipunjwani** [comment]
+1

**Comment by gevgeny** [comment]
Yes, sorry for the delay

**Comment by fank** [comment]
See https://github.com/gevgeny/angular2-highcharts/issues/64#issuecomment-249513601
