### ISSUE TITLE
ERROR in [default] node_modules/angular2-highcharts/dist/ChartComponent.d.ts 

### ISSUE THREAD

**Issue by SamD** [gevgeny/angular2-highcharts#97]
Cannot find name 'HighchartsChartObject'.

Getting this when attempting to use the module as described with an angular-cli project

**Comment by Sfairet** [comment]
Have same problem, after reinstall node modules with same package.json, that work fine before.

```
node_modules/angular2-highcharts/dist/ChartComponent.d.ts(12,26): error TS2304: Cannot find name 'HighchartsChartObject'.
node_modules/angular2-highcharts/dist/ChartComponent.d.ts(22,12): error TS2304: Cannot find name 'HighchartsChartObject'.
node_modules/angular2-highcharts/dist/ChartComponent.d.ts(28,14): error TS2304: Cannot find name 'HighchartsOptions'.
node_modules/angular2-highcharts/dist/ChartEvent.d.ts(4,14): error TS2304: Cannot find name 'HighchartsChartObject'.
node_modules/angular2-highcharts/dist/ChartEvent.d.ts(4,38): error TS2304: Cannot find name 'HighchartsSeriesObject'.
node_modules/angular2-highcharts/dist/ChartEvent.d.ts(4,63): error TS2304: Cannot find name 'HighchartsPointObject'.
node_modules/angular2-highcharts/dist/ChartEvent.d.ts(4,87): error TS2304: Cannot find name 'HighchartsAxisObject'.
node_modules/angular2-highcharts/dist/HighchartsService.d.ts(3,17): error TS2304: Cannot find name 'HighchartsStatic'.
```

package.json:

```
{
  "name": "name",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w --project tsconfig_wathcer.json",
    "typings": "typings"
  },
  "license": "Commercial",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular2-highcharts": "^0.3.3",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.2",
    "highcharts": "^4.2.6",
    "ng2-translate": "^2.4.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings": "^1.3.2"
  }
}
```

**Comment by SamD** [comment]
Was there a fix for this? why was it closed?

I had the same experience as @Sfairet , my initial version worked but then on Friday it stopped, I'm going to hazard a guess it is possibly related to a dependency change?

**Comment by Sfairet** [comment]
@SamD i think issue was closed, because new version available `angular2-highcharts@0.4.1`.
But in new version i have same problem on compilation. 
I find very simple solution - just change `HighchartsOptions` to `Object` type. Against [readme.md](https://github.com/gevgeny/angular2-highcharts/blob/master/README.md) that method used in this [example](https://github.com/gevgeny/angular2-quickstart-and-angular2-highcharts/commit/5021ff2b7f615a5b566b4bab0faf70991f5a53db).
@gevgeny it is right? And this method must use for System JS only or it is misprint in [README.md](https://github.com/gevgeny/angular2-highcharts/blob/master/README.md) or in [angular2-quickstart-and-angular2-highcharts](https://github.com/gevgeny/angular2-quickstart-and-angular2-highcharts/commit/5021ff2b7f615a5b566b4bab0faf70991f5a53db)?

**Comment by gevgeny** [comment]
Yes, sorry I have not fixed README.md examples with `HighchartsOptions`. New highcharts typings has no any `HighchartsOptions`. Look at these examples https://github.com/gevgeny/angular2-highcharts/blob/master/README.md#installation. And let me know if it works

**Comment by Sfairet** [comment]
@gevgeny angular/quickstart (SystemJS) work fine, thank you!
